### ISSUE TITLE
如何使用显卡加速

### ISSUE THREAD

**Issue by w123456w30w** [opteroncx/MoePhoto#14]
如题，我该如何使用显卡加速，而且工具支持调用TensorCore吗？

**Comment by opteroncx** [comment]
自动检测的，如果有显卡就用显卡，没有显卡就用CPU跑。
除了插帧其他都是半精度的，Volta架构会调用

**Comment by w123456w30w** [comment]
> 自动检测的，如果有显卡就用显卡，没有显卡就用CPU跑。
> 除了插帧其他都是半精度的，Volta架构会调用

抱歉最近没有看邮箱，我安装了CUDA但是在进行处理的时候显卡没有任何负载，CPU占用很高，然后我显卡是图灵架构的，可以调用TensorCore吗？

**Comment by opteroncx** [comment]
请单独看cuda的占用率，或者你跑一张图片放大看速度，CPU模式得要数十秒，如果几秒就跑完就可以确认是GPU模式。
