### ISSUE TITLE
Moire pattern removal

### ISSUE THREAD

**Issue by excllent123** [opteroncx/MoePhoto#28]
Hi

   看到您在ICCV2019关于去摩尔纹的文章，请问会开源吗？
 
谢谢

**Comment by opteroncx** [comment]
你好，这几周事情比较多没有时间整理（代码比较乱），后面整理好会开源的。

**Comment by excllent123** [comment]
楼主好，您可以把没整理好的代码发邮箱吗,我的邮箱是m201472483@alumni.hust.edu.cn
= = 希望对比和您论文的试验结果
Thanks

**Comment by opteroncx** [comment]
我尽量在这个周末整理开源

**Comment by excllent123** [comment]
谢谢楼主
