### ISSUE TITLE
如何确认自己使用了GPU

### ISSUE THREAD

**Issue by xplorld** [opteroncx/MoePhoto#51]
如题，任务管理器声称 MoePhoto.exe 只利用了单核CPU，没有利用GPU. 另外有办法强制开启GPU吗？

**Comment by opteroncx** [comment]
方法1：查看萌图系统信息页面，看是否检测到GPU
方法2：电脑任务管理器-GPU-把顶部折线图旋转cuda
方法3：GPU-Z查看显卡占用
